stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/prepare_base_model_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/prepare_base_model_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/cnnClassifier/pipeline/model_trainer_pipeline.py
    deps:
      - src/cnnClassifier/pipeline/model_trainer_pipeline.py
      - src/cnnClassifier/components/prepare_callback.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/cnnClassifier/pipeline/model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false